INCLUDE_PATH    := ./ ../external/include/ ../common/ ../gl_util/
SOURCE_PATH     := ./ ../common/ ../gl_util/
DEPENDENCY_PATH := dep
OBJECT_PATH     := obj

EXTERNAL_LIBS := $(wildcard ../external/lib/*.a)
LDLIBS := -lm -lpthread -lglut -lGL -lGLU


include ../makefile.mk
